name: OpenWrt ImageBuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y build-essential zstd xz-utils

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/24.10.5/targets/x86/64/openwrt-imagebuilder-24.10.5-x86-64.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xf openwrt-imagebuilder-24.10.5-x86-64.Linux-x86_64.tar.zst

      - name: Build image
        run: |
          cd openwrt-imagebuilder-24.10.5-x86-64.Linux-x86_64
          make image PROFILE=generic ROOTFS_PARTSIZE=2048 \
          PACKAGES="luci luci-base luci-compat luci-ssl bash curl ca-bundle unzip ip-full ipset dnsmasq-full -dnsmasq ruby ruby-yaml kmod-tun kmod-inet-diag iptables iptables-mod-tproxy iptables-mod-extra"

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-x86
          path: openwrt-imagebuilder-24.10.5-x86-64.Linux-x86_64/bin/targets/x86/64/*
